// ─── Rich mock vendors with unique Unsplash images ───────────────────────────
export const MOCK_VENDORS = [
  {
    id: 1,
    name: "Ravi Kirana Store",
    category: "Kirana",
    address: "12, RS Puram, Coimbatore",
    distanceKm: 0.4,
    rating: 4.7,
    reviewCount: 128,
    trustScore: 94,
    status: "open",
    hasIot: true,
    iotLive: true,
    lastSeen: "just now",
    viewCount: 87,
    colorBg: "#FFF3E0",
    emoji: "🛒",
    // Unique shop banner
    bannerImg: "https://images.unsplash.com/photo-1604719312566-8912e9667d9f?w=600&q=85",
    // Unique shop avatar/profile
    avatarImg: "https://images.unsplash.com/photo-1542838132-92c53300491e?w=200&q=85",
    description: "Your trusted neighbourhood kirana. Fresh stock daily, best prices guaranteed.",
    openHours: "6 AM – 10 PM",
    tags: ["Daily Essentials", "Groceries", "IoT Verified"],
  },
  {
    id: 2,
    name: "Sri Murugan Vegetables",
    category: "Vegetables",
    address: "45, Gandhipuram, Coimbatore",
    distanceKm: 0.8,
    rating: 4.5,
    reviewCount: 96,
    trustScore: 89,
    status: "open",
    hasIot: false,
    iotLive: false,
    lastSeen: "—",
    viewCount: 54,
    colorBg: "#E8F5E9",
    emoji: "🥦",
    bannerImg: "https://images.unsplash.com/photo-1488459716781-31db52582fe9?w=600&q=85",
    avatarImg: "https://images.unsplash.com/photo-1518977956812-cd3dbadaaf31?w=200&q=85",
    description: "Farm-fresh vegetables sourced directly from Ooty farmers every morning.",
    openHours: "5 AM – 9 PM",
    tags: ["Farm Fresh", "Organic", "Daily Delivery"],
  },
  {
    id: 3,
    name: "Amul Dairy Corner",
    category: "Dairy",
    address: "7, Peelamedu, Coimbatore",
    distanceKm: 1.1,
    rating: 4.8,
    reviewCount: 210,
    trustScore: 97,
    status: "open",
    hasIot: true,
    iotLive: true,
    lastSeen: "3 min ago",
    viewCount: 143,
    colorBg: "#E3F2FD",
    emoji: "🥛",
    bannerImg: "https://images.unsplash.com/photo-1550583724-b2692b85b150?w=600&q=85",
    avatarImg: "https://images.unsplash.com/photo-1563636619-e9143da7973b?w=200&q=85",
    description: "Authorised Amul parlour. Milk, curd, paneer, butter — all fresh and cold-chain maintained.",
    openHours: "6 AM – 10 PM",
    tags: ["Cold Chain", "Amul Authorised", "IoT Verified"],
  },
  {
    id: 4,
    name: "Lakshmi Provision Store",
    category: "Provision",
    address: "23, Saibaba Colony, Coimbatore",
    distanceKm: 1.4,
    rating: 4.3,
    reviewCount: 74,
    trustScore: 82,
    status: "open",
    hasIot: true,
    iotLive: true,
    lastSeen: "10 min ago",
    viewCount: 39,
    colorBg: "#FFF9C4",
    emoji: "🧺",
    bannerImg: "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=600&q=85",
    avatarImg: "https://images.unsplash.com/photo-1578916171728-46686eac8d58?w=200&q=85",
    description: "Wide range of provisions, masalas, pulses and packaged goods. Est. 1998.",
    openHours: "7 AM – 9:30 PM",
    tags: ["Provisions", "Masala", "Pulses"],
  },
  {
    id: 5,
    name: "Fresh Fruit Junction",
    category: "Fruits",
    address: "88, Town Hall Road, Coimbatore",
    distanceKm: 1.7,
    rating: 4.6,
    reviewCount: 152,
    trustScore: 91,
    status: "open",
    hasIot: false,
    iotLive: false,
    lastSeen: "—",
    viewCount: 98,
    colorBg: "#FBE9E7",
    emoji: "🍊",
    bannerImg: "https://images.unsplash.com/photo-1610832958506-aa56368176cf?w=600&q=85",
    avatarImg: "https://images.unsplash.com/photo-1619566636858-adf3ef46400b?w=200&q=85",
    description: "Seasonal and exotic fruits from across Tamil Nadu. Seasonal specials every week.",
    openHours: "7 AM – 8 PM",
    tags: ["Seasonal", "Exotic Fruits", "Weekly Deals"],
  },
  {
    id: 6,
    name: "Nandha Super Market",
    category: "Kirana",
    address: "3, Singanallur, Coimbatore",
    distanceKm: 2.0,
    rating: 4.2,
    reviewCount: 88,
    trustScore: 78,
    status: "open",
    hasIot: false,
    iotLive: false,
    lastSeen: "—",
    viewCount: 61,
    colorBg: "#EDE7F6",
    emoji: "🏪",
    bannerImg: "https://images.unsplash.com/photo-1523474253046-8cd2748b5fd2?w=600&q=85",
    avatarImg: "https://images.unsplash.com/photo-1528698827591-e19ccd7bc23d?w=200&q=85",
    description: "Full-range supermarket with household items, groceries, and personal care.",
    openHours: "8 AM – 10 PM",
    tags: ["Supermarket", "Household", "Personal Care"],
  },
  {
    id: 7,
    name: "Kavitha Organic Farm",
    category: "Vegetables",
    address: "15, Vadavalli, Coimbatore",
    distanceKm: 2.3,
    rating: 4.9,
    reviewCount: 67,
    trustScore: 96,
    status: "open",
    hasIot: true,
    iotLive: true,
    lastSeen: "1 min ago",
    viewCount: 72,
    colorBg: "#E8F5E9",
    emoji: "🌿",
    bannerImg: "https://images.unsplash.com/photo-1464226184884-fa280b87c399?w=600&q=85",
    avatarImg: "https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?w=200&q=85",
    description: "100% certified organic produce. No pesticides. Straight from our farm to your table.",
    openHours: "6 AM – 7 PM",
    tags: ["100% Organic", "Certified", "IoT Verified"],
  },
  {
    id: 8,
    name: "Selvam Milk Depot",
    category: "Dairy",
    address: "56, Ukkadam, Coimbatore",
    distanceKm: 2.8,
    rating: 4.4,
    reviewCount: 113,
    trustScore: 85,
    status: "closed",
    hasIot: true,
    iotLive: false,
    lastSeen: "2 hr ago",
    viewCount: 29,
    colorBg: "#E3F2FD",
    emoji: "🥛",
    bannerImg: "https://images.unsplash.com/photo-1499781350541-7783f6c6a0c8?w=600&q=85",
    avatarImg: "https://images.unsplash.com/photo-1550989460-0adf9ea622e2?w=200&q=85",
    description: "Fresh cow milk, A2 milk, and homemade curd. Subscription delivery available.",
    openHours: "5 AM – 9 AM, 4 PM – 8 PM",
    tags: ["A2 Milk", "Subscription", "Home Delivery"],
  },
  {
    id: 9,
    name: "Raja Dry Fruits & Nuts",
    category: "Provision",
    address: "101, Big Bazaar Street, Coimbatore",
    distanceKm: 3.1,
    rating: 4.6,
    reviewCount: 184,
    trustScore: 93,
    status: "open",
    hasIot: false,
    iotLive: false,
    lastSeen: "—",
    viewCount: 115,
    colorBg: "#FFF3E0",
    emoji: "🥜",
    bannerImg: "https://images.unsplash.com/photo-1599599810694-b5b37304c041?w=600&q=85",
    avatarImg: "https://images.unsplash.com/photo-1508061253366-f7da158b6d46?w=200&q=85",
    description: "Premium dry fruits, nuts, and spices imported and local. Gift packs available.",
    openHours: "9 AM – 9 PM",
    tags: ["Dry Fruits", "Gift Packs", "Premium"],
  },
  {
    id: 10,
    name: "Mango Paradise",
    category: "Fruits",
    address: "77, Hopes College, Coimbatore",
    distanceKm: 3.5,
    rating: 4.8,
    reviewCount: 222,
    trustScore: 90,
    status: "open",
    hasIot: true,
    iotLive: true,
    lastSeen: "5 min ago",
    viewCount: 188,
    colorBg: "#FFFDE7",
    emoji: "🥭",
    bannerImg: "https://images.unsplash.com/photo-1553279768-865429fa0078?w=600&q=85",
    avatarImg: "https://images.unsplash.com/photo-1601493700631-2b16ec4b4716?w=200&q=85",
    description: "Alphonso, Banganapalli, Kesar — 12 varieties of mangoes. Season: April–July.",
    openHours: "8 AM – 9 PM",
    tags: ["12 Varieties", "Seasonal", "IoT Verified"],
  },
];

// Category images for filter tiles
export const CATEGORY_IMAGES = {
  All:        "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=200&q=80",
  Kirana:     "https://images.unsplash.com/photo-1604719312566-8912e9667d9f?w=200&q=80",
  Vegetables: "https://images.unsplash.com/photo-1488459716781-31db52582fe9?w=200&q=80",
  Dairy:      "https://images.unsplash.com/photo-1550583724-b2692b85b150?w=200&q=80",
  Provision:  "https://images.unsplash.com/photo-1599599810694-b5b37304c041?w=200&q=80",
  Fruits:     "https://images.unsplash.com/photo-1610832958506-aa56368176cf?w=200&q=80",
};

// Mock prices per vendor
export const MOCK_PRICES = {
  1: [ // Ravi Kirana
    { product: { id: 1, name: "Tomato",  unit: "kg", category: "Vegetables" }, price: 42 },
    { product: { id: 2, name: "Onion",   unit: "kg", category: "Vegetables" }, price: 35 },
    { product: { id: 3, name: "Rice",    unit: "kg", category: "Provision"  }, price: 68 },
    { product: { id: 4, name: "Sugar",   unit: "kg", category: "Provision"  }, price: 44 },
    { product: { id: 5, name: "Milk",    unit: "L",  category: "Dairy"      }, price: 56 },
  ],
  2: [ // Murugan Vegetables
    { product: { id: 1, name: "Tomato",   unit: "kg", category: "Vegetables" }, price: 38 },
    { product: { id: 2, name: "Onion",    unit: "kg", category: "Vegetables" }, price: 32 },
    { product: { id: 6, name: "Brinjal",  unit: "kg", category: "Vegetables" }, price: 28 },
    { product: { id: 7, name: "Carrot",   unit: "kg", category: "Vegetables" }, price: 45 },
    { product: { id: 8, name: "Spinach",  unit: "bunch", category: "Vegetables" }, price: 15 },
  ],
  3: [ // Amul Dairy
    { product: { id: 5, name: "Milk",       unit: "L",  category: "Dairy" }, price: 54 },
    { product: { id: 9, name: "Curd",       unit: "kg", category: "Dairy" }, price: 48 },
    { product: { id: 10, name: "Paneer",    unit: "kg", category: "Dairy" }, price: 340 },
    { product: { id: 11, name: "Butter",    unit: "100g",category:"Dairy" }, price: 56 },
    { product: { id: 12, name: "Ice Cream", unit: "L",  category: "Dairy" }, price: 180 },
  ],
  4: [
    { product: { id: 3, name: "Rice",  unit: "kg", category: "Provision" }, price: 65 },
    { product: { id: 4, name: "Sugar", unit: "kg", category: "Provision" }, price: 42 },
    { product: { id: 13, name: "Dal",  unit: "kg", category: "Provision" }, price: 95 },
    { product: { id: 14, name: "Atta", unit: "kg", category: "Provision" }, price: 52 },
  ],
  5: [
    { product: { id: 15, name: "Apple",   unit: "kg", category: "Fruits" }, price: 180 },
    { product: { id: 16, name: "Banana",  unit: "doz",category: "Fruits" }, price: 38 },
    { product: { id: 17, name: "Grapes",  unit: "kg", category: "Fruits" }, price: 95 },
    { product: { id: 18, name: "Papaya",  unit: "kg", category: "Fruits" }, price: 45 },
  ],
};

// Mock reviews per vendor
export const MOCK_REVIEWS = {
  1: [
    { id: 1, userName: "Priya S", rating: 5, text: "Best kirana store in RS Puram! Always fresh and prices are very fair.", date: "2 days" },
    { id: 2, userName: "Karthik R", rating: 4, text: "Good variety of products. Staff is friendly and helpful.", date: "1 week" },
    { id: 3, userName: "Meena K", rating: 5, text: "Love that they have IoT price updates — always know the latest rates!", date: "2 weeks" },
  ],
  2: [
    { id: 4, userName: "Anand B", rating: 5, text: "Freshest vegetables in Gandhipuram. They get Ooty veggies every morning!", date: "3 days" },
    { id: 5, userName: "Sudha M", rating: 4, text: "Good quality, slightly pricey but worth it for the freshness.", date: "1 week" },
  ],
  3: [
    { id: 6, userName: "Rajesh P", rating: 5, text: "Amul products are always fresh here. Cold chain is maintained properly.", date: "1 day" },
    { id: 7, userName: "Lakshmi V", rating: 5, text: "Best dairy products in Peelamedu. Trust score is well deserved!", date: "4 days" },
    { id: 8, userName: "Arjun K", rating: 4, text: "Good stock but sometimes runs out of paneer on weekends.", date: "1 week" },
  ],
};

// Sample IoT device for Admin (always shown)
export const SAMPLE_IOT_DEVICES = [
  { id: 101, name: "Ravi Kirana Store",      model: "ESP8266 NodeMCU", live: true,  lastSeen: "just now", uptime: "99%", signal: "-65dBm", latency: "0.9s", vendorId: 1 },
  { id: 102, name: "Amul Dairy Corner",      model: "ESP32 DevKit",   live: true,  lastSeen: "3 min ago",uptime: "97%", signal: "-70dBm", latency: "1.2s", vendorId: 3 },
  { id: 103, name: "Lakshmi Provision Store",model: "ESP8266 NodeMCU", live: false, lastSeen: "2 hr ago", uptime: "81%", signal: "—",      latency: "—",   vendorId: 4 },
  { id: 104, name: "Kavitha Organic Farm",   model: "ESP32 DevKit",   live: true,  lastSeen: "1 min ago",uptime: "98%", signal: "-68dBm", latency: "1.1s", vendorId: 7 },
  { id: 105, name: "Mango Paradise",         model: "ESP8266 NodeMCU", live: true,  lastSeen: "5 min ago",uptime: "95%", signal: "-72dBm", latency: "1.4s", vendorId: 10 },
  { id: 106, name: "Selvam Milk Depot",      model: "ESP32 DevKit",   live: false, lastSeen: "3 hr ago", uptime: "74%", signal: "—",      latency: "—",   vendorId: 8 },
];

// Mock products for admin products tab
export const MOCK_PRODUCTS_ADMIN = [
  { id: 1,  name: "Tomato",   category: "Vegetables", unit: "kg",   avgPrice: 40,  img: "https://images.unsplash.com/photo-1546470427-e26264be0b0d?w=80&q=80",  trend: "up",   trendPct: "+5%" },
  { id: 2,  name: "Onion",    category: "Vegetables", unit: "kg",   avgPrice: 34,  img: "https://images.unsplash.com/photo-1508747703725-719777637510?w=80&q=80", trend: "down", trendPct: "-3%" },
  { id: 3,  name: "Rice",     category: "Provision",  unit: "kg",   avgPrice: 66,  img: "https://images.unsplash.com/photo-1536304993881-ff86e0c9c3d7?w=80&q=80", trend: "up",   trendPct: "+2%" },
  { id: 4,  name: "Sugar",    category: "Provision",  unit: "kg",   avgPrice: 43,  img: "https://images.unsplash.com/photo-1528698827591-e19ccd7bc23d?w=80&q=80", trend: "down", trendPct: "-1%" },
  { id: 5,  name: "Milk",     category: "Dairy",      unit: "L",    avgPrice: 55,  img: "https://images.unsplash.com/photo-1563636619-e9143da7973b?w=80&q=80",   trend: "up",   trendPct: "+4%" },
  { id: 6,  name: "Brinjal",  category: "Vegetables", unit: "kg",   avgPrice: 27,  img: "https://images.unsplash.com/photo-1615484477778-ca3b77940c25?w=80&q=80", trend: "down", trendPct: "-8%" },
  { id: 7,  name: "Banana",   category: "Fruits",     unit: "doz",  avgPrice: 38,  img: "https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?w=80&q=80", trend: "up",   trendPct: "+6%" },
  { id: 8,  name: "Apple",    category: "Fruits",     unit: "kg",   avgPrice: 175, img: "https://images.unsplash.com/photo-1568702846914-96b305d2aaeb?w=80&q=80", trend: "down", trendPct: "-2%" },
  { id: 9,  name: "Paneer",   category: "Dairy",      unit: "kg",   avgPrice: 335, img: "https://images.unsplash.com/photo-1588166524941-3bf61a9c41db?w=80&q=80", trend: "up",   trendPct: "+7%" },
  { id: 10, name: "Dal",      category: "Provision",  unit: "kg",   avgPrice: 92,  img: "https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=80&q=80", trend: "up",   trendPct: "+3%" },
];
